package com.github.eclipsethemes.eclipse.preferences;

public interface PreferenceKeys {
	String ACTIVE_THEME_ID = "ACTIVE_THEME_ID";
	String APPLY_WORKBENCH_THEME = "APPLY_WORKBENCH_THEME";
	String ENABLE_ECLIPSE_CSS_MODERNIZATION = "ENABLE_ECLIPSE_CSS_MODERNIZATION";
	String ENABLE_GTK_MODERNIZATION = "ENABLE_GTK_MODERNIZATION";
	String COLOR_CUSTOMIZATIONS_PREFIX = "COLOR_CUSTOMIZATIONS.";
}
