package com.github.eclipsethemes.eclipse.adapters.ui;

import java.util.LinkedHashMap;
import java.util.Map;

import com.github.eclipsethemes.core.models.Theme;

/**
 * Generates the GTK stylesheet that covers what Eclipse CSS cannot reach.
 *
 * <p>
 * SWT delegates the painting of {@code Text}, {@code Combo}, {@code Button},
 * menus, tooltips, scrollbars and every selection highlight to GTK, and the e4
 * CSS engine has no property for those. Only literal selectors are used
 * because GTK resolves {@code @define-color} per provider, so the names below
 * would not reach the rules of the desktop theme.
 * </p>
 */
public final class GtkCssGenerator {

	private GtkCssGenerator() {
	}

	public static String generate(Theme theme) {
		WorkbenchPalette palette = WorkbenchPalette.of(theme);

		Map<String, String> colors = new LinkedHashMap<>();
		colors.put("background", palette.background());
		colors.put("foreground", palette.foreground());
		colors.put("chrome", palette.chrome());
		colors.put("elevated", palette.elevated());
		colors.put("hover", palette.hover());
		colors.put("input", palette.input());
		colors.put("border", palette.border());
		colors.put("muted", palette.muted());
		colors.put("disabled", palette.disabled());
		colors.put("link", palette.link());
		colors.put("selectionBackground", palette.selectionBackground());
		colors.put("selectionForeground", palette.selectionForeground());

		String css = TEMPLATE;
		for (Map.Entry<String, String> color : colors.entrySet()) {
			css = css.replace("${" + color.getKey() + "}", color.getValue());
		}
		return css;
	}

	// @formatter:off
	private static final String TEMPLATE = """
			/* Generated by Eclipse Themes. Changes are overwritten. */
			@define-color theme_bg_color ${background};
			@define-color theme_fg_color ${foreground};
			@define-color theme_base_color ${input};
			@define-color theme_text_color ${foreground};
			@define-color theme_selected_bg_color ${selectionBackground};
			@define-color theme_selected_fg_color ${selectionForeground};
			@define-color borders ${border};
			@define-color insensitive_fg_color ${disabled};

			window, dialog, .background {
			    background-color: ${background};
			    color: ${foreground};
			}

			/* GTK containers must stay transparent. Painting them would also paint
			 * the box and label nodes GTK nests inside buttons and combos, which
			 * shows up as a differently colored rectangle inside the control. SWT
			 * paints its own composites from the Eclipse stylesheet anyway.
			 */
			box, paned, grid, viewport, scrolledwindow, stack, overlay,
			button box, button label, button image {
			    background-color: transparent;
			}

			label, image {
			    color: ${foreground};
			}

			label:disabled, label:insensitive, *:disabled, *:insensitive {
			    color: ${disabled};
			}

			entry, spinbutton, textview, textview text, .entry {
			    background-color: ${input};
			    background-image: none;
			    color: ${foreground};
			    border-color: ${border};
			}

			entry:focus, spinbutton:focus {
			    border-color: ${link};
			}

			entry selection, textview text selection, label selection {
			    background-color: ${selectionBackground};
			    color: ${selectionForeground};
			}

			/* Push buttons sit slightly above the surface. Using the darker chrome
			 * color here makes them read as holes punched into the dialog. The
			 * border matches the fill and the GTK shadows are dropped, otherwise
			 * the desktop theme outlines every button in a contrasting color.
			 */
			button {
			    background-color: ${elevated};
			    background-image: none;
			    color: ${foreground};
			    border-color: ${elevated};
			    box-shadow: none;
			    text-shadow: none;
			}

			button:hover {
			    background-color: ${hover};
			    background-image: none;
			    color: ${foreground};
			    border-color: ${hover};
			    box-shadow: none;
			}

			button:active, button:checked {
			    background-color: ${selectionBackground};
			    background-image: none;
			    color: ${selectionForeground};
			    border-color: ${selectionBackground};
			    box-shadow: none;
			}

			button:disabled {
			    background-color: ${background};
			    background-image: none;
			    color: ${disabled};
			    border-color: ${background};
			    box-shadow: none;
			}

			button:focus {
			    outline-color: ${link};
			}

			/* Toolbars, headers and tab bars paint their own surface, so the buttons
			 * on them stay flat until hovered.
			 */
			toolbar button, toolbar togglebutton, headerbar button, notebook button, button.flat {
			    background-color: transparent;
			    background-image: none;
			    border-color: transparent;
			    box-shadow: none;
			}

			toolbar button:hover, toolbar togglebutton:hover, headerbar button:hover,
			notebook button:hover, button.flat:hover {
			    background-color: ${hover};
			    background-image: none;
			}

			combobox button, combobox button:hover, spinbutton button {
			    background-color: ${input};
			    background-image: none;
			    color: ${foreground};
			}

			menubar, menu, .menu, .context-menu, popover, popover.background, .popup {
			    background-color: ${chrome};
			    color: ${foreground};
			}

			menuitem, menubar > menuitem {
			    color: ${foreground};
			}

			menuitem:hover, menubar > menuitem:hover {
			    background-color: ${selectionBackground};
			    color: ${selectionForeground};
			}

			tooltip, tooltip.background, tooltip label {
			    background-color: ${elevated};
			    color: ${foreground};
			}

			treeview.view, treeview, list, list row, iconview {
			    background-color: ${background};
			    color: ${foreground};
			}

			treeview.view:hover, list row:hover {
			    background-color: ${hover};
			}

			treeview.view header button {
			    background-color: ${elevated};
			    background-image: none;
			    color: ${foreground};
			    border-color: ${border};
			}

			notebook, notebook header, notebook header tabs, toolbar, headerbar, .titlebar {
			    background-color: ${chrome};
			    color: ${foreground};
			}

			notebook tab:checked {
			    background-color: ${background};
			    color: ${foreground};
			}

			separator, .separator {
			    background-color: ${border};
			    color: ${border};
			}

			scrollbar, scrollbar trough {
			    background-color: ${chrome};
			    border-color: ${border};
			}

			scrollbar slider {
			    background-color: ${border};
			}

			scrollbar slider:hover {
			    background-color: ${muted};
			}

			progressbar trough, .progressbar trough {
			    background-color: ${elevated};
			}

			progressbar progress, .progressbar progress {
			    background-color: ${link};
			}

			check, radio {
			    background-color: ${input};
			    background-image: none;
			    border-color: ${border};
			    color: ${foreground};
			}

			check:checked, radio:checked {
			    background-color: ${link};
			    background-image: none;
			    color: ${background};
			}

			*:selected, *:selected:focus, treeview.view:selected,
			treeview.view:selected:focus, list row:selected, list:selected, entry:selected {
			    background-color: ${selectionBackground};
			    color: ${selectionForeground};
			}
			""";
	// @formatter:on
}
